sugarcube-2:
  macros:
    horny_reset:
      name: horny_reset
    video:
      name: video
    companionList:
      name: companionList
    time24hr:
      name: time24hr
    timeDay:
      name: timeDay
    timeCycle:
      name: timeCycle
    gameDay:
      name: gameDay
    showmeter:
      name: showmeter
    perkList:
      name: perkList
    flag:
      name: flag
